In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings('ignore')

2023-08-25 17:28:10.103842: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-25 17:28:10.105123: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-25 17:28:10.133950: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-25 17:28:10.134558: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-25 17:28:10.778884: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [3]:
titanic=pd.read_csv(r'./final_dataset_ready.csv')
dataset=titanic.copy()
X=np.asarray(dataset.drop('Survived',axis=1))
y=np.asarray(dataset['Survived'])
print('X',X,'\ny',y)

X [[ 3.  1. 22. ...  0.  0.  1.]
 [ 1.  0. 38. ...  1.  0.  0.]
 [ 3.  0. 26. ...  0.  0.  1.]
 ...
 [ 3.  0. 28. ...  0.  0.  1.]
 [ 1.  1. 26. ...  1.  0.  0.]
 [ 3.  1. 32. ...  0.  1.  0.]] 
y [0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 

In [4]:
dataset

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  \
0           0       3    1  22.0      1      0   7.2500           0   
1           1       1    0  38.0      1      0  71.2833           1   
2           1       3    0  26.0      0      0   7.9250           0   
3           1       1    0  35.0      1      0  53.1000           0   
4           0       3    1  35.0      0      0   8.0500           0   
..        ...     ...  ...   ...    ...    ...      ...         ...   
886         0       2    1  27.0      0      0  13.0000           0   
887         1       1    0  19.0      0      0  30.0000           0   
888         0       3    0  28.0      1      2  23.4500           0   
889         1       1    1  26.0      0      0  30.0000           1   
890         0       3    1  32.0      0      0   7.7500           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 10 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
X_test.shape

(179, 9)

In [29]:
sc = StandardScaler()
X_train_normalized = sc.fit_transform(X_train)
X_test_normalized = sc.transform(X_test)

In [30]:
X_train_normalized.shape[1]

9

In [124]:
numDims = X_train_normalized.shape[1]
dnnModel = tf.keras.Sequential([    
    layers.Dense(16, activation='elu', input_shape=(numDims,)),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(16, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.3),
    layers.Dense(126, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(160, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(10, activation='relu'),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(2)
])
optimizer = tf.keras.optimizers.RMSprop(0.001)
dnnModel.compile(optimizer=optimizer,loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])



In [125]:
dnnModel.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_84 (Dense)            (None, 16)                160       
                                                                 
 batch_normalization_70 (Ba  (None, 16)                64        
 tchNormalization)                                               
                                                                 
 dropout_70 (Dropout)        (None, 16)                0         
                                                                 
 dense_85 (Dense)            (None, 16)                272       
                                                                 
 batch_normalization_71 (Ba  (None, 16)                64        
 tchNormalization)                                               
                                                                 
 dropout_71 (Dropout)        (None, 16)              

In [126]:
dnnModel.fit(X_train_normalized,y_train,epochs=100)

Epoch 1/100
23/23 [==============================] - 1s 1ms/step - loss: 0.7636 - accuracy: 0.5829
Epoch 2/100
23/23 [==============================] - 0s 1ms/step - loss: 0.7270 - accuracy: 0.6039
Epoch 3/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6932 - accuracy: 0.6615
Epoch 4/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6562 - accuracy: 0.6601
Epoch 5/100
23/23 [==============================] - 0s 2ms/step - loss: 0.6273 - accuracy: 0.6896
Epoch 6/100
23/23 [==============================] - 0s 2ms/step - loss: 0.6209 - accuracy: 0.6854
Epoch 7/100
23/23 [==============================] - 0s 2ms/step - loss: 0.6042 - accuracy: 0.7037
Epoch 8/100
23/23 [==============================] - 0s 1ms/step - loss: 0.6040 - accuracy: 0.6966
Epoch 9/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5862 - accuracy: 0.7289
Epoch 10/100
23/23 [==============================] - 0s 2ms/step - loss: 0.5696 - accuracy: 0.7191
Epoch 11/

23/23 [==============================] - 0s 1ms/step - loss: 0.4511 - accuracy: 0.8146
Epoch 84/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4640 - accuracy: 0.8062
Epoch 85/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4679 - accuracy: 0.7992
Epoch 86/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4509 - accuracy: 0.8062
Epoch 87/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4390 - accuracy: 0.8104
Epoch 88/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8132
Epoch 89/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4530 - accuracy: 0.8048
Epoch 90/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4424 - accuracy: 0.8216
Epoch 91/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4625 - accuracy: 0.8118
Epoch 92/100
23/23 [==============================] - 0s 1ms/step - loss: 0.4616 - accuracy: 0.8076
Epoch 93/100


In [127]:
test_loss, test_acc = dnnModel.evaluate(X_test_normalized,  y_test, verbose=2)
print('\nTest accuracy:', test_acc)

6/6 - 0s - loss: 0.4313 - accuracy: 0.7933 - 116ms/epoch - 19ms/step

Test accuracy: 0.7932960987091064


In [128]:
y_pred = np.argmax(dnnModel.predict(X_test),axis=1)

6/6 [==============================] - 0s 1ms/step


In [91]:
idx = np.random.randint(1,len(y_test))
print('Index = ',idx,'  Predicted::',y_pred[idx],'  Actual::',y_test[idx])

Index =  89   Predicted:: 0   Actual:: 0
